modLoader = "javafml"
loaderVersion = "[${loader_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "KilaBash, screret, Mikerooni, serenibyss, Tech22"
description = "${mod_description}"
logoFile = "icon.png"
displayURL = "${mod_url}"
credits = "GregoriusT, Mr_Touchyou, Zerrens for making GregTech and textures, the GT5u authors and maintainers for providing the original code, and the community."

[[mixins]]
config="${mod_id}.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0.0-alpha,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "ldlib"
    type = "required"
    versionRange = "[1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "kubejs"
    type = "optional"
    versionRange = "[${kjs_version},)"
    ordering = "AFTER"
    side = "BOTH"


#[features.${mod_id}]
#openGLVersion = "[3.2,)"
