modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "KilaBash, screret, serenibyss, Tech22, YoungOnion, Mikerooni, Ghostipedia"
description = "${mod_description}"
logoFile = "icon.png"
displayURL = "${mod_url}"
credits = "GregoriusT, Mr_Touchyou, Zerrens for making GregTech and textures, the GT5u authors and maintainers for providing the original code, and the community."

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ldlib"
mandatory = true
versionRange = "[${ldlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "configuration"
mandatory = true
versionRange = "[${configuration_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = false
versionRange = "[${kjs_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "emi"
mandatory = false
versionRange = "[${emi_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "theoneprobe"
mandatory = false
versionRange = "[${top_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jade"
mandatory = false
versionRange = "[${jade_version},)"
ordering = "NONE"
side = "BOTH"
