name: auto-build

on:
  push:
    branches:
      - 'sc/intermediary-1.20.5-port'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTION_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
      GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Get Version
        id: var
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | grep dev.jar -v | grep slim.jar -v | grep all.jar -v | awk -F 'gtceu-|.jar' '{print $2}')
          echo version=$MESSAGE >> $GITHUB_OUTPUT

      - name: Release
        id: release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          github-tag: ${{ steps.var.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar

      - name: Print Output
        run: |
          echo "Release tag: ${{ steps.release.outputs.github-tag }}"
          echo "Release URL: ${{ steps.release.outputs.github-url }}"
          echo "Released files: ${{ steps.release.outputs.github-files }}"
